name: Deploy Portfolio

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # 3️⃣ Install dependencies, skip optional to avoid Rollup native errors
      - name: Install dependencies
        run: npm ci --ignore-optional

      # 4️⃣ Build the project
      - name: Build
        run: npm run build

      # 5️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Optional: set branch explicitly if you want
          # publish_branch: gh-pages
